pelagos_data_repository_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DataRepositoryController

pelagos_funding_cycle_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\FundingCycleController

pelagos_funding_organization_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\FundingOrganizationController

pelagos_person_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PersonController

pelagos_person_funding_organization_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PersonFundingOrganizationController

pelagos_person_research_group_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PersonResearchGroupController

pelagos_research_group_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\ResearchGroupController

pelagos_person_data_repository_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PersonDataRepositoryController

pelagos_account_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\AccountController

pelagos_dif_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DIFController

pelagos_dataset_submission_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetSubmissionController

pelagos_datset_monitoring_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetMonitoringController

pelagos_dataset_summary_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetSummaryController

pelagos_publication_dataset_link_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PublicationDatasetLinkController

pelagos_dataland_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatalandController

pelagos_tombstone_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\TombstoneController

pelagos_stats_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\StatsController

pelagos_mdapp_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\MdAppController

pelagos_data_discovery_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DataDiscoveryController

pelagos_report_researchgroup_dataset_dif_controller_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\ReportResearchGroupDatasetStatusController

pelagos_gomri_reports_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\GomriReportController

pelagos_dataset_restrictions_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetRestrictionsController

pelagos_dataset_download_report_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetDownloadReportController

pelagos_search_terms_report_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\SearchTermsReportController

pelagos_dataset_review_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetReviewController

pelagos_end_review_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\EndReviewController

pelagos_national_data_center_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\NationalDataCenterController

pelagos_side_by_side_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\SideBySideController
